export const TOGGLE_TRACK_FORM = 'TOGGLE_TRACK_FROM';
export const ADD_TRACK = 'ADD_TRACK';
export const DELETE_TRACK = 'DELETE_TRACK';
export const UPDATE_TRACK = 'UPDATE_TRACK';
export const CLEAR_TRACK_DETAILS = 'CLEAR_TRACK_DETAILS';
export const SET_TRACK_DETAILS = 'SET_TRACK_DETAILS';
